[package]
name = "rustls-libssl"
version = "0.1.0"
edition = "2021"
build = "build.rs"
rust-version = "1.77"

[lib]
name = "ssl"
crate-type = ["cdylib"]

[dependencies]
env_logger = "0.10"
log = "0.4"
openssl-probe = "0.1"
openssl-sys = "0.9.98"
rustls = "0.23"
rustls-pemfile = "2"
